### ISSUE TITLE
Cannot compile EMQ after adding emq_kafka_bridge

### ISSUE THREAD

**Issue by dxGuan** [iotblue/emq_kafka_bridge#12]
I use emq v2.3.11 and I can compile it successfully without any problem.

However, after adding emq_kafka_bridge(go through the steps exactly in the guidance) and compiled with error, which something like this:

make[2]: Leaving directory '/home/derrick/Works/EMQ/emqx-rel/deps/jwerl'
 DEPEND emq_auth_jwt.d
 ERLC   emq_auth_jwt.erl emq_auth_jwt_app.erl emq_auth_jwt_config.erl
 APP    emq_auth_jwt
make[1]: Leaving directory '/home/derrick/Works/EMQ/emqx-rel/deps/emq_auth_jwt'
make[1]: Entering directory '/home/derrick/Works/EMQ/emqx-rel/deps/emq_kafka_bridge'
 DEP    ekaf
make[2]: Entering directory '/home/derrick/Works/EMQ/emqx-rel/deps/ekaf'
 DEP    kafkamocker
make[3]: Entering directory '/home/derrick/Works/EMQ/emqx-rel/deps/kafkamocker'
 DEP    ranch
make[4]: Entering directory '/home/derrick/Works/EMQ/emqx-rel/deps/ranch'
 DEPEND ranch.d
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_crc32c.erl ranch_listener_sup.erl ranch_protocol.erl ranch_proxy_header.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
src/ranch_proxy_header.erl:23: syntax error before: ':='
src/ranch_proxy_header.erl:592: type proxy_info() undefined
../../erlang.mk:1174: recipe for target 'ebin/ranch.app' failed
make[5]: *** [ebin/ranch.app] Error 1
../../erlang.mk:992: recipe for target 'app' failed
make[4]: *** [app] Error 2
make[4]: Leaving directory '/home/derrick/Works/EMQ/emqx-rel/deps/ranch'
../../erlang.mk:312: recipe for target 'deps' failed
make[3]: *** [deps] Error 2
make[3]: Leaving directory '/home/derrick/Works/EMQ/emqx-rel/deps/kafkamocker'
../../erlang.mk:312: recipe for target 'deps' failed
make[2]: *** [deps] Error 2
make[2]: Leaving directory '/home/derrick/Works/EMQ/emqx-rel/deps/ekaf'
../../erlang.mk:312: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/home/derrick/Works/EMQ/emqx-rel/deps/emq_kafka_bridge'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2

How can I deal with it?

**Comment by iotblue** [comment]
Hello,

please make sure to add the following lines in EMQ_rex make file

in `DEPS +=`  add the following at the end of the deps `emq_kafka_bridge`
```
DEPS += emqttd emq_modules emq_dashboard emq_retainer emq_recon emq_reloader \
        emq_auth_clientid emq_auth_username emq_auth_ldap emq_auth_http \
        emq_auth_mysql emq_auth_pgsql emq_auth_redis emq_auth_mongo \
        emq_sn emq_coap emq_stomp emq_plugin_template emq_web_hook \
        emq_lua_hook emq_auth_jwt emq_kafka_bridge
```

also you need to add the following line after web_hook

```
# kafka
# replace with your own repo if needed
dep_emq_kafka_bridge  = git https://github.com/iotblue/emq_kafka_bridge v2.3.11 
```
and add the following line to relx.config
find `{emq_plugin_template, load},`
then add the below line
 **{emq_kafka_bridge, load}**

**Comment by dxGuan** [comment]
I had completely followed you instructions to compile emqtt with emq_kafka_bridge.

However, it fails again with exactly the same error:

```
make[1]: Entering directory '/home/derrick/Works/EMQ/emq-relx/deps/emq_kafka_bridge'
 DEP    ekaf
make[2]: Entering directory '/home/derrick/Works/EMQ/emq-relx/deps/ekaf'
 DEP    kafkamocker
make[3]: Entering directory '/home/derrick/Works/EMQ/emq-relx/deps/kafkamocker'
 DEP    ranch
make[4]: Entering directory '/home/derrick/Works/EMQ/emq-relx/deps/ranch'
 DEPEND ranch.d
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_crc32c.erl ranch_listener_sup.erl ranch_protocol.erl ranch_proxy_header.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
src/ranch_proxy_header.erl:23: syntax error before: ':='
src/ranch_proxy_header.erl:592: type proxy_info() undefined
../../erlang.mk:1174: recipe for target 'ebin/ranch.app' failed
make[5]: *** [ebin/ranch.app] Error 1
../../erlang.mk:992: recipe for target 'app' failed
make[4]: *** [app] Error 2
make[4]: Leaving directory '/home/derrick/Works/EMQ/emq-relx/deps/ranch'
../../erlang.mk:312: recipe for target 'deps' failed
make[3]: *** [deps] Error 2
make[3]: Leaving directory '/home/derrick/Works/EMQ/emq-relx/deps/kafkamocker'
../../erlang.mk:312: recipe for target 'deps' failed
make[2]: *** [deps] Error 2
make[2]: Leaving directory '/home/derrick/Works/EMQ/emq-relx/deps/ekaf'
../../erlang.mk:312: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/home/derrick/Works/EMQ/emq-relx/deps/emq_kafka_bridge'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2
```

---------------

My environment

* Ubunut 16.04 LTS

* Erlang/OTP 18 

* emqx-relx tag:v2.3.11

**Comment by iotblue** [comment]
Ok so environment may be the reason for this error, because as of emq have requirements

EMQ 2.2-rc.2. Requires Erlang/OTP R19.3+ to build 
https://github.com/emqx/emqx-rel/blob/v2.3.11/README.md#emq-relx 

so I think you need to update Erlang/OTP version

**Comment by iotblue** [comment]
Erlang/OTP R19.3+ to build is required to build since EMQ 2.2-rc.2

**Comment by iotblue** [comment]
Erlang/OTP R19.3+ to build is required to build since EMQ 2.2-rc.2
