### ISSUE TITLE
Kafka does not receive any message on 'Payload' topic

### ISSUE THREAD

**Issue by Clan-Utility** [iotblue/emq_kafka_bridge#18]
Erlang/OTP 20
CentOS 7.4.1708
EMQ v2.3.11 
kafka_2.11-2.1.0 (started as [https://kafka.apache.org/quickstart#quickstart_startserver](https://kafka.apache.org/quickstart#quickstart_startserver))

emqx-rel/Makefile

    DEPS += emqttd emq_modules emq_retainer emq_recon emq_reloader \
        emq_auth_http \
        emq_sn emq_coap emq_stomp emq_plugin_template emq_web_hook \
        emq_lua_hook emq_kafka_bridge

    # COVER = true
    #NO_AUTOPATCH = emq_elixir_plugin
    dep_emq_kafka_bridge  = git https://github.com/iotblue/emq_kafka_bridge v2.3.11
    include erlang.mk

emq-rel/relx.config

    %%{emq_auth_clientid, load},
    %%{emq_auth_username, load},
    %%{emq_auth_ldap, load},
    {emq_auth_http, load},
    %%{emq_auth_mongo, load},
    %%{emq_auth_mysql, load},
    %%{emq_auth_pgsql, load},
    %%{emq_auth_redis, load},
    %%{emq_auth_jwt, load},
    {emq_plugin_template, load},
    {emq_kafka_bridge, load}

emqx-rel/_rel/emqttd/etc/plugins/emq_kafka_bridge.conf

    kafka.host = localhost

    kafka.port = 12345

    kafka.partitionstrategy = random

    kafka.partitionworkers = 1

    kafka.payloadtopic = Payload

    kafka.eventtopic = Event

emqttd_ctl plugins list shows:
Plugin(emq_auth_http, version=2.3.11, description=Authentication/ACL with HTTP API, active=false)
Plugin(emq_coap, version=2.3.11, description=CoAP Gateway, active=false)
Plugin(emq_kafka_bridge, version=2.3.11, description=EMQ Kafka Bridge, active=true)
Plugin(emq_lua_hook, version=2.3.11, description=EMQ Hooks in lua, active=false)
Plugin(emq_modules, version=2.3.11, description=EMQ Modules, active=true)
Plugin(emq_plugin_template, version=2.3.11, description=EMQ Plugin Template, active=false)
Plugin(emq_recon, version=2.3.11, description=Recon Plugin, active=true)
Plugin(emq_reloader, version=2.3.11, description=Reloader Plugin, active=false)
Plugin(emq_retainer, version=2.3.11, description=EMQ Retainer, active=true)
Plugin(emq_sn, version=2.3.11, description=MQTT-SN Gateway, active=false)
Plugin(emq_stomp, version=2.3.11, description=Stomp Protocol Plugin, active=false)
Plugin(emq_web_hook, version=2.3.11, description=EMQ Webhook Plugin, active=false)

Client uses mqtt.js

    var client  = mqtt.connect('mqtt://localhost:1883')
    client.on('connect', function () {
      client.publish('presence', hello);
    });

But kafka is unable to receive message on either Payload or Event topic.

**Comment by Clan-Utility** [comment]
Seems like topics "Processing" and "DeviceLog" are working

**Comment by Clan-Utility** [comment]
in emq_kafka_bridge.erl
produce_kafka_payload/1 & produce_kafka_log/1
Change 

    ok = ekaf:produce_async(Topic, Payload)

to

    ok = ekaf:produce_async(list_to_binary(Topic), Payload)

**Comment by iotblue** [comment]
Resolved 7a16e48e08e01ad926a8f0841fad86eb9d86f0f1
