### ISSUE TITLE
What if Kafka is temporarily unavailable?

### ISSUE THREAD

**Issue by Clan-Utility** [iotblue/emq_kafka_bridge#24]
Are all the messages lost during this period? Is there a way to buffer all the messages and send later?

**Comment by iotblue** [comment]
By default all messages are queued untill kafka connection is initiated again to be sent to kafka

**Comment by iotblue** [comment]
![image](https://user-images.githubusercontent.com/18533943/52540103-8d418c80-2d8e-11e9-9f6e-cd2634d1063c.png)
